### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mitchmindtree** [MaikKlein/rlsl#40]
Hi @MaikKlein, this project looks super exciting, please keep up the great work!

I'm currently working on a creative coding framework and would love to allow users to use something like RLSL in the future for graphics and compute. I'd like to contribute at some point, but would appreciate it if you could clarify your plans for the licensing of RLSL first. FWIW, I'd love something close to the license used by Rust itself, but this is of course just my opinion!

**Comment by MaikKlein** [comment]
Oops thanks for the catch. I'll add the license in a few minutes, it will be the same license that rustc uses. This should be MIT / APACHE

**Comment by MaikKlein** [comment]
I added the MIT and APACHE license. If that doesn't suit you feel free to reopen the issue or open a new one. 

I'll keep an eye on your creative coding framework, and I'll let you know when rlsl is ready to be tested.
