### ISSUE TITLE
A logo for rlsl

### ISSUE THREAD

**Issue by MaikKlein** [MaikKlein/rlsl#49]
I would appreciate it very much if anyone would like to design a logo for rlsl as I am not a very good artist myself. 

I am also working on a GPU path tracer with a friend, maybe I can create some nice looking fractals in the future that could be used as a logo.

**Comment by dannyfritz** [comment]
I created an SVG in InkScape:

![rlsl2](https://user-images.githubusercontent.com/315788/41374053-5a9faca0-6f0f-11e8-883b-c7a251a262ff.png)

---

<details>
<summary><b>Inspiration:</b></summary>
<img src="https://user-images.githubusercontent.com/315788/41373853-c2a28620-6f0e-11e8-9b84-3f1cad0b4a1d.png">
<img src="https://user-images.githubusercontent.com/315788/41373884-d3bd09d0-6f0e-11e8-9884-9f0851f64186.png">
</details>

**Comment by Limeth** [comment]
I like it a lot, although I found a slight issue with the shape of the curve. It seems that the inner cutout is some kind of ellipsoid, but your recreation doesn't exactly mimic the geometry of the original. In the original, the curve envelops the inner ellipsoid, whereas in the recreation, the ellipsoid is overlapped. See the following pictures:
![spir](https://user-images.githubusercontent.com/1978878/41406671-4c59dfa8-6fcd-11e8-8a7d-c7e293cdec99.png)
![rlsl](https://user-images.githubusercontent.com/1978878/41406673-4e5da73a-6fcd-11e8-8043-1df0d19072d1.png)
I add other Khronos logos for reference, to illustrate that the inner ellipsoid retains its shape even when used around longer labels:
![serveimage](https://user-images.githubusercontent.com/1978878/41407280-3a98b382-6fcf-11e8-94d5-79488f65b6d1.jpeg)
![serveimage2](https://user-images.githubusercontent.com/1978878/41407281-3c12ce50-6fcf-11e8-81d0-66088cd90a93.jpeg)

**Comment by Limeth** [comment]
Additionally, the font that they use in their logos seems to be
```
	Main Font: Helvetica Neue 55 Roman, Helvetica Neue 75 Bold
	TM/Registered TM: Helvetica Neue 75 Bold
```
(found in the SPIR Logo Pack at https://www.khronos.org/legal/trademarks/)

**Comment by dannyfritz** [comment]
I did a trace to match the curve of the SPIR logo. I also don't have access
to helvetica. Arial is the closest I have.

I can share the svg where you can see the curve matches the reference and
change the font.

Danny

**Comment by MaikKlein** [comment]
@dannyfritz Thanks for creating the logo :). Would you like to make a PR and put the svg file somewhere under `media/`? 

Also I am not sure if the logo is too similar to the SPIR logo. It might invoke the wrong impression that this in an official Khronos project.

**Comment by dannyfritz** [comment]
Heh, let's consider it a good talking point to get more people interested in making a logo in that case. :wink:

**Comment by MaikKlein** [comment]
Someone is giving away logos for open source projects. https://github.com/arasatasaygin/openlogos. Do you see a fitting logo for rlsl on there?
