### ISSUE TITLE
Generating storage buffers

### ISSUE THREAD

**Issue by MaikKlein** [MaikKlein/rlsl#54]
Currently glslang decorates a struct with `BufferBlock`. But `BufferBlock` has been deprecated.

> BufferBlock
Deprecated (use Block-decorated StorageBuffer Storage Class objects).
Apply to a structure type to establish it is an SSBO-like shader-interface block.

The spec recommends to use the `StorageBuffer` storage class, but this requires the following extensions `SPV_KHR_storage_buffer_storage_class, SPV_KHR_variable_pointers`

Only ~30% of the gpus support those extensions pre 1.1, but they have been made core in 1.1. 

Now what should rlsl target? `BufferBlock` or `StorageBuffer` or both?

**Comment by MaikKlein** [comment]
I'll probably still implement the deprecated BufferBlock variant. We can still feature gate the StorageBuffer class later.

**Comment by minecrawler** [comment]
I'd say always go with the latest spec. If anyone needs older functionality, they should use an older LTS version. That way, you keep open for future improvements, but enable people to go back to older version if needed.

**Comment by MaikKlein** [comment]
I am going to support both, the change appears to be trivial. For now I am going with the deprecated version because gfx still uses an Vulkan 1.0 context. I also need to push ash to version 1.1.
