### ISSUE TITLE
Is this still alive?

### ISSUE THREAD

**Issue by deprilula28** [MaikKlein/rlsl#73]
I'm sorry for spamming the issues board, but I don't know any other way to contact the creators. Is this still alive?

**Comment by keithsim-msft** [comment]
😢

**Comment by zanayr** [comment]
@MaikKlein, I too would like to know if this is still alive? If you tagged some issues for beginners, I would like to help out where I can. Best,

**Comment by Kethku** [comment]
I suspect there are many who would like to help out on this project

**Comment by nilsmartel** [comment]
Also curious, but I guess this is on ice for now

**Comment by MaikKlein** [comment]
I am going to release some information about it soonish, but can't give an exact date for it yet :).

**Comment by nilsmartel** [comment]
@MaikKlein this is very much fine, there's no need for an exact date or anything.
But I think your work here is amazing and it inspires so much. I'd like to follow as closely as possible, is there some place I can subscribe to your updates?

**Comment by MaikKlein** [comment]
@nilsmartel https://twitter.com/MaikKlein_DEV or https://maikklein.github.io/

**Comment by MaikKlein** [comment]
You can find the blog post here https://maikklein.github.io/rlsl-update3/
